Add pre-commit
Yelp/pysensu-yelp pull request #33
Opened 2022-08-31 00:29 UTC by ymilki

Adding pre-commit for strong opinions on style and syntax. In particular, ensuring consistency for py3.

2022-09-01 17:59 UTC, benbariteau requested changes

2022-09-01 17:59 UTC, benbariteau commented on pysensu_yelp/__init__.py
> +)  # 1 second
This comment got misplaced

2022-09-01 21:37 UTC, ymilki commented on pysensu_yelp/__init__.py
> +)  # 1 second
Fixed this.

2022-09-07 21:15 UTC, benbariteau approved these changes

2022-09-07 21:27 UTC, merged